[project]
name = "advent-of-code-25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ruff>=0.14.7",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
